CREATE TABLE IF NOT EXISTS `IT202_S24_RECIPES` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `recipe_link` VARCHAR(255) NOT NULL,
    `calories` DECIMAL(10,2) NOT NULL,
    `totalTime` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`name`)
);