CREATE TABLE IF NOT EXISTS `IT202-S24-AUTHORS` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `book_id` INT NOT NULL,
    `author` VARCHAR(255) NOT NULL,
    FOREIGN KEY (`book_id`) REFERENCES `IT202-S24-BOOKS`(`id`) ON DELETE CASCADE
);